import java.awt.EventQueue;

import javax.swing.JFrame;

import java.awt.GridBagLayout;

import javax.swing.JPanel;

import java.awt.GridBagConstraints;
import java.awt.Insets;

import javax.swing.JLabel;
import javax.swing.BoxLayout;

import java.awt.BorderLayout;
import java.awt.Color;

import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JTextArea;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.util.HashMap;


/**
 *
 *This class was autoGenerated by the eclipse plugin WindowBuilder.
 *To use the gui builder check this site https://projects.eclipse.org/projects/tools.windowbuilder for more information
 
 *Button action listener are located at the bottom of the text for handling button events
 * @author tudor.tibu@ryerson.ca
 *  If anything is confusing please feel free to email me.
 *    */
public class GUI {

	private JFrame frame;
	private JTextField txtEnterSerial;
	private JTextField txtSerialSearch;
	private JTextField txtTitleSearch;
	private JTextField txtArtistSearch;
	private JTextField txtAlbumSearch;
	private JTextField txtYearSearch;
	private JTextField txtTypeSearch;
	private JTextField txtLocationSearch;
	private JTextField txtTitleSubmit;
	private JTextField txtSerialSubmit;
	private JTextField txtArtistSubmit;
	private JTextField txtAlbumSubmit;
	private JTextField txtYearSubmit;
	private JTextField txtTypeSubmit;
	private JTextField txtLocationSubmit;
	private JTextField txtClientName;
	private JTextField txtEnterClientId;
	private JTextField txtClientIDSearch;
	private JTextField txtFnameSearch;
	private JTextField txtLnameSearch;
	private JTextField txtLoanedSearch;
	private JTextField txtClientIDSubmit;
	private JTextField txtFnameSubmit;
	private JTextField txtLnameSubmit;

	ItemDbManager itemDb;
	ClientDbManager clientDb;
	private JTextField txtEmailSubmit;
	private JTextField txtEmailSearch;

	/**
	 * Create the application.
	 */
	public GUI(ItemDbManager itemDb, ClientDbManager clientDb) {
		this.itemDb =itemDb;
		this.clientDb = clientDb;
		initialize();
		this.frame.setVisible(true);
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize() {
		frame = new JFrame();
		frame.getContentPane().setBackground(Color.YELLOW);
		GridBagLayout gridBagLayout = new GridBagLayout();
		gridBagLayout.columnWidths = new int[]{413, 379, 306, 0};
		gridBagLayout.rowHeights = new int[]{0, 0, 0};
		gridBagLayout.columnWeights = new double[]{1.0, 1.0, 1.0, Double.MIN_VALUE};
		gridBagLayout.rowWeights = new double[]{0.0, 1.0, Double.MIN_VALUE};
		frame.getContentPane().setLayout(gridBagLayout);
		
		JPanel panel_2 = new JPanel();
		panel_2.setBackground(new Color(211, 211, 211));
		GridBagConstraints gbc_panel_2 = new GridBagConstraints();
		gbc_panel_2.gridheight = 2;
		gbc_panel_2.insets = new Insets(0, 0, 0, 5);
		gbc_panel_2.fill = GridBagConstraints.BOTH;
		gbc_panel_2.gridx = 0;
		gbc_panel_2.gridy = 0;
		frame.getContentPane().add(panel_2, gbc_panel_2);
		GridBagLayout gbl_panel_2 = new GridBagLayout();
		gbl_panel_2.columnWidths = new int[]{0, 133, 0, 126, 0, 0};
		gbl_panel_2.rowHeights = new int[]{1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 37, 23, 0, 0, 0, 0, 0, 0, 0, 0, 0};
		gbl_panel_2.columnWeights = new double[]{0.0, 1.0, 0.0, 1.0, 0.0, Double.MIN_VALUE};
		gbl_panel_2.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		panel_2.setLayout(gbl_panel_2);
		
		JLabel lblSearchABook = new JLabel("Search an Item");
		GridBagConstraints gbc_lblSearchABook = new GridBagConstraints();
		gbc_lblSearchABook.insets = new Insets(0, 0, 5, 5);
		gbc_lblSearchABook.gridx = 1;
		gbc_lblSearchABook.gridy = 1;
		panel_2.add(lblSearchABook, gbc_lblSearchABook);
		
		txtEnterSerial = new JTextField();
		txtEnterSerial.setText("Search By Serial Number");
		GridBagConstraints gbc_txtEnterSerial = new GridBagConstraints();
		gbc_txtEnterSerial.insets = new Insets(0, 0, 5, 5);
		gbc_txtEnterSerial.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtEnterSerial.gridx = 1;
		gbc_txtEnterSerial.gridy = 2;
		panel_2.add(txtEnterSerial, gbc_txtEnterSerial);
		txtEnterSerial.setColumns(10);
		
		JButton btnItemSearch = new JButton("Search");
				
		
		GridBagConstraints gbc_btnItemSearch = new GridBagConstraints();
		gbc_btnItemSearch.insets = new Insets(0, 0, 5, 5);
		gbc_btnItemSearch.gridx = 1;
		gbc_btnItemSearch.gridy = 3;
		panel_2.add(btnItemSearch, gbc_btnItemSearch);
		
		JLabel lblSearchResults = new JLabel("Search Results");
		GridBagConstraints gbc_lblSearchResults = new GridBagConstraints();
		gbc_lblSearchResults.fill = GridBagConstraints.VERTICAL;
		gbc_lblSearchResults.insets = new Insets(0, 0, 5, 5);
		gbc_lblSearchResults.gridx = 3;
		gbc_lblSearchResults.gridy = 4;
		panel_2.add(lblSearchResults, gbc_lblSearchResults);
		
		JLabel lblSerialNumber = new JLabel("Serial Number");
		GridBagConstraints gbc_lblSerialNumber = new GridBagConstraints();
		gbc_lblSerialNumber.insets = new Insets(0, 0, 5, 5);
		gbc_lblSerialNumber.gridx = 1;
		gbc_lblSerialNumber.gridy = 5;
		panel_2.add(lblSerialNumber, gbc_lblSerialNumber);
		
		JLabel lblBookTitle = new JLabel("Title");
		GridBagConstraints gbc_lblBookTitle = new GridBagConstraints();
		gbc_lblBookTitle.insets = new Insets(0, 0, 5, 5);
		gbc_lblBookTitle.gridx = 3;
		gbc_lblBookTitle.gridy = 5;
		panel_2.add(lblBookTitle, gbc_lblBookTitle);
		
		txtSerialSearch = new JTextField();
		txtSerialSearch.setEditable(false);
		GridBagConstraints gbc_txtSerialSearch = new GridBagConstraints();
		gbc_txtSerialSearch.insets = new Insets(0, 0, 5, 5);
		gbc_txtSerialSearch.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtSerialSearch.gridx = 1;
		gbc_txtSerialSearch.gridy = 6;
		panel_2.add(txtSerialSearch, gbc_txtSerialSearch);
		txtSerialSearch.setColumns(10);
		
		txtTitleSearch = new JTextField();
		txtTitleSearch.setEditable(false);
		GridBagConstraints gbc_txtTitleSearch = new GridBagConstraints();
		gbc_txtTitleSearch.insets = new Insets(0, 0, 5, 5);
		gbc_txtTitleSearch.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtTitleSearch.gridx = 3;
		gbc_txtTitleSearch.gridy = 6;
		panel_2.add(txtTitleSearch, gbc_txtTitleSearch);
		txtTitleSearch.setColumns(10);
		
		JLabel lblNewLabel_2 = new JLabel("Artist");
		GridBagConstraints gbc_lblNewLabel_2 = new GridBagConstraints();
		gbc_lblNewLabel_2.insets = new Insets(0, 0, 5, 5);
		gbc_lblNewLabel_2.gridx = 1;
		gbc_lblNewLabel_2.gridy = 7;
		panel_2.add(lblNewLabel_2, gbc_lblNewLabel_2);
		
		JLabel lblNewLabel_3 = new JLabel("Album");
		GridBagConstraints gbc_lblNewLabel_3 = new GridBagConstraints();
		gbc_lblNewLabel_3.anchor = GridBagConstraints.ABOVE_BASELINE;
		gbc_lblNewLabel_3.insets = new Insets(0, 0, 5, 5);
		gbc_lblNewLabel_3.gridx = 3;
		gbc_lblNewLabel_3.gridy = 7;
		panel_2.add(lblNewLabel_3, gbc_lblNewLabel_3);
		
		txtArtistSearch = new JTextField();
		txtArtistSearch.setEditable(false);
		GridBagConstraints gbc_txtArtistSearch = new GridBagConstraints();
		gbc_txtArtistSearch.insets = new Insets(0, 0, 5, 5);
		gbc_txtArtistSearch.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtArtistSearch.gridx = 1;
		gbc_txtArtistSearch.gridy = 8;
		panel_2.add(txtArtistSearch, gbc_txtArtistSearch);
		txtArtistSearch.setColumns(10);
		
		txtAlbumSearch = new JTextField();
		txtAlbumSearch.setEditable(false);
		GridBagConstraints gbc_txtAlbumSearch = new GridBagConstraints();
		gbc_txtAlbumSearch.insets = new Insets(0, 0, 5, 5);
		gbc_txtAlbumSearch.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtAlbumSearch.gridx = 3;
		gbc_txtAlbumSearch.gridy = 8;
		panel_2.add(txtAlbumSearch, gbc_txtAlbumSearch);
		txtAlbumSearch.setColumns(10);
		
		JLabel lblNewLabel_4 = new JLabel("Year");
		GridBagConstraints gbc_lblNewLabel_4 = new GridBagConstraints();
		gbc_lblNewLabel_4.insets = new Insets(0, 0, 5, 5);
		gbc_lblNewLabel_4.gridx = 1;
		gbc_lblNewLabel_4.gridy = 9;
		panel_2.add(lblNewLabel_4, gbc_lblNewLabel_4);
		
		JLabel lblNewLabel_5 = new JLabel("Type");
		GridBagConstraints gbc_lblNewLabel_5 = new GridBagConstraints();
		gbc_lblNewLabel_5.insets = new Insets(0, 0, 5, 5);
		gbc_lblNewLabel_5.gridx = 3;
		gbc_lblNewLabel_5.gridy = 9;
		panel_2.add(lblNewLabel_5, gbc_lblNewLabel_5);
		
		txtYearSearch = new JTextField();
		txtYearSearch.setEditable(false);
		GridBagConstraints gbc_txtYearSearch = new GridBagConstraints();
		gbc_txtYearSearch.insets = new Insets(0, 0, 5, 5);
		gbc_txtYearSearch.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtYearSearch.gridx = 1;
		gbc_txtYearSearch.gridy = 10;
		panel_2.add(txtYearSearch, gbc_txtYearSearch);
		txtYearSearch.setColumns(10);
		
		txtTypeSearch = new JTextField();
		txtTypeSearch.setEditable(false);
		GridBagConstraints gbc_txtTypeSearch = new GridBagConstraints();
		gbc_txtTypeSearch.insets = new Insets(0, 0, 5, 5);
		gbc_txtTypeSearch.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtTypeSearch.gridx = 3;
		gbc_txtTypeSearch.gridy = 10;
		panel_2.add(txtTypeSearch, gbc_txtTypeSearch);
		txtTypeSearch.setColumns(10);
		
		JLabel label = new JLabel("");
		GridBagConstraints gbc_label = new GridBagConstraints();
		gbc_label.insets = new Insets(0, 0, 5, 5);
		gbc_label.gridx = 1;
		gbc_label.gridy = 11;
		panel_2.add(label, gbc_label);
		
		JLabel lblNewLabel_6 = new JLabel("Location");
		GridBagConstraints gbc_lblNewLabel_6 = new GridBagConstraints();
		gbc_lblNewLabel_6.insets = new Insets(0, 0, 5, 5);
		gbc_lblNewLabel_6.gridx = 1;
		gbc_lblNewLabel_6.gridy = 12;
		panel_2.add(lblNewLabel_6, gbc_lblNewLabel_6);
		
		txtLocationSearch = new JTextField();
		txtLocationSearch.setEditable(false);
		GridBagConstraints gbc_txtLocationSearch = new GridBagConstraints();
		gbc_txtLocationSearch.insets = new Insets(0, 0, 5, 5);
		gbc_txtLocationSearch.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtLocationSearch.gridx = 1;
		gbc_txtLocationSearch.gridy = 13;
		panel_2.add(txtLocationSearch, gbc_txtLocationSearch);
		txtLocationSearch.setColumns(10);
		
		JLabel lblAddAnItem = new JLabel("Add an Item");
		GridBagConstraints gbc_lblAddAnItem = new GridBagConstraints();
		gbc_lblAddAnItem.insets = new Insets(0, 0, 5, 5);
		gbc_lblAddAnItem.gridx = 3;
		gbc_lblAddAnItem.gridy = 15;
		panel_2.add(lblAddAnItem, gbc_lblAddAnItem);
		
		JLabel label_1 = new JLabel("Serial Number");
		GridBagConstraints gbc_label_1 = new GridBagConstraints();
		gbc_label_1.insets = new Insets(0, 0, 5, 5);
		gbc_label_1.gridx = 1;
		gbc_label_1.gridy = 16;
		panel_2.add(label_1, gbc_label_1);
		
		JLabel label_4 = new JLabel("Title");
		GridBagConstraints gbc_label_4 = new GridBagConstraints();
		gbc_label_4.insets = new Insets(0, 0, 5, 5);
		gbc_label_4.gridx = 3;
		gbc_label_4.gridy = 16;
		panel_2.add(label_4, gbc_label_4);
		
		txtSerialSubmit = new JTextField();
		GridBagConstraints gbc_txtSerialSubmit = new GridBagConstraints();
		gbc_txtSerialSubmit.insets = new Insets(0, 0, 5, 5);
		gbc_txtSerialSubmit.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtSerialSubmit.gridx = 1;
		gbc_txtSerialSubmit.gridy = 17;
		panel_2.add(txtSerialSubmit, gbc_txtSerialSubmit);
		txtSerialSubmit.setColumns(10);
		
		txtTitleSubmit = new JTextField();
		GridBagConstraints gbc_txtTitleSubmit = new GridBagConstraints();
		gbc_txtTitleSubmit.insets = new Insets(0, 0, 5, 5);
		gbc_txtTitleSubmit.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtTitleSubmit.gridx = 3;
		gbc_txtTitleSubmit.gridy = 17;
		panel_2.add(txtTitleSubmit, gbc_txtTitleSubmit);
		txtTitleSubmit.setColumns(10);
		
		JLabel label_2 = new JLabel("Artist");
		GridBagConstraints gbc_label_2 = new GridBagConstraints();
		gbc_label_2.insets = new Insets(0, 0, 5, 5);
		gbc_label_2.gridx = 1;
		gbc_label_2.gridy = 18;
		panel_2.add(label_2, gbc_label_2);
		
		JLabel label_5 = new JLabel("Album");
		GridBagConstraints gbc_label_5 = new GridBagConstraints();
		gbc_label_5.insets = new Insets(0, 0, 5, 5);
		gbc_label_5.gridx = 3;
		gbc_label_5.gridy = 18;
		panel_2.add(label_5, gbc_label_5);
		
		txtArtistSubmit = new JTextField();
		GridBagConstraints gbc_txtArtistSubmit = new GridBagConstraints();
		gbc_txtArtistSubmit.insets = new Insets(0, 0, 5, 5);
		gbc_txtArtistSubmit.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtArtistSubmit.gridx = 1;
		gbc_txtArtistSubmit.gridy = 19;
		panel_2.add(txtArtistSubmit, gbc_txtArtistSubmit);
		txtArtistSubmit.setColumns(10);
		
		txtAlbumSubmit = new JTextField();
		GridBagConstraints gbc_txtAlbumSubmit = new GridBagConstraints();
		gbc_txtAlbumSubmit.insets = new Insets(0, 0, 5, 5);
		gbc_txtAlbumSubmit.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtAlbumSubmit.gridx = 3;
		gbc_txtAlbumSubmit.gridy = 19;
		panel_2.add(txtAlbumSubmit, gbc_txtAlbumSubmit);
		txtAlbumSubmit.setColumns(10);
		
		JLabel label_3 = new JLabel("Year");
		GridBagConstraints gbc_label_3 = new GridBagConstraints();
		gbc_label_3.insets = new Insets(0, 0, 5, 5);
		gbc_label_3.gridx = 1;
		gbc_label_3.gridy = 20;
		panel_2.add(label_3, gbc_label_3);
		
		JLabel label_6 = new JLabel("Type");
		GridBagConstraints gbc_label_6 = new GridBagConstraints();
		gbc_label_6.insets = new Insets(0, 0, 5, 5);
		gbc_label_6.gridx = 3;
		gbc_label_6.gridy = 20;
		panel_2.add(label_6, gbc_label_6);
		
		txtYearSubmit = new JTextField();
		GridBagConstraints gbc_txtYearSubmit = new GridBagConstraints();
		gbc_txtYearSubmit.insets = new Insets(0, 0, 5, 5);
		gbc_txtYearSubmit.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtYearSubmit.gridx = 1;
		gbc_txtYearSubmit.gridy = 21;
		panel_2.add(txtYearSubmit, gbc_txtYearSubmit);
		txtYearSubmit.setColumns(10);
		
		txtTypeSubmit = new JTextField();
		GridBagConstraints gbc_txtTypeSubmit = new GridBagConstraints();
		gbc_txtTypeSubmit.anchor = GridBagConstraints.NORTH;
		gbc_txtTypeSubmit.insets = new Insets(0, 0, 5, 5);
		gbc_txtTypeSubmit.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtTypeSubmit.gridx = 3;
		gbc_txtTypeSubmit.gridy = 21;
		panel_2.add(txtTypeSubmit, gbc_txtTypeSubmit);
		txtTypeSubmit.setColumns(10);
		
		JLabel label_7 = new JLabel("Location");
		GridBagConstraints gbc_label_7 = new GridBagConstraints();
		gbc_label_7.insets = new Insets(0, 0, 5, 5);
		gbc_label_7.gridx = 1;
		gbc_label_7.gridy = 22;
		panel_2.add(label_7, gbc_label_7);
		
		txtLocationSubmit = new JTextField();
		GridBagConstraints gbc_txtLocationSubmit = new GridBagConstraints();
		gbc_txtLocationSubmit.insets = new Insets(0, 0, 5, 5);
		gbc_txtLocationSubmit.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtLocationSubmit.gridx = 1;
		gbc_txtLocationSubmit.gridy = 23;
		panel_2.add(txtLocationSubmit, gbc_txtLocationSubmit);
		txtLocationSubmit.setColumns(10);
		
		JButton btnItemSubmit = new JButton("Submit");
		
		GridBagConstraints gbc_btnItemSubmit = new GridBagConstraints();
		gbc_btnItemSubmit.insets = new Insets(0, 0, 5, 5);
		gbc_btnItemSubmit.gridx = 3;
		gbc_btnItemSubmit.gridy = 23;
		panel_2.add(btnItemSubmit, gbc_btnItemSubmit);
		
		JLabel labelItemInvalid = new JLabel("");
		labelItemInvalid.setEnabled(true);
		labelItemInvalid.setForeground(Color.RED);
		GridBagConstraints gbc_labelItemInvalid = new GridBagConstraints();
		gbc_labelItemInvalid.insets = new Insets(0, 0, 0, 5);
		gbc_labelItemInvalid.gridx = 3;
		gbc_labelItemInvalid.gridy = 24;
		panel_2.add(labelItemInvalid, gbc_labelItemInvalid);
		
		JPanel panel_1 = new JPanel();
		panel_1.setBackground(new Color(211, 211, 211));
		GridBagConstraints gbc_panel_1 = new GridBagConstraints();
		gbc_panel_1.gridheight = 2;
		gbc_panel_1.insets = new Insets(0, 0, 0, 5);
		gbc_panel_1.fill = GridBagConstraints.BOTH;
		gbc_panel_1.gridx = 1;
		gbc_panel_1.gridy = 0;
		frame.getContentPane().add(panel_1, gbc_panel_1);
		GridBagLayout gbl_panel_1 = new GridBagLayout();
		gbl_panel_1.columnWidths = new int[]{0, 0, 0, 0, 0, 0, 0};
		gbl_panel_1.rowHeights = new int[]{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
		gbl_panel_1.columnWeights = new double[]{0.0, 1.0, 0.0, 1.0, 0.0, 0.0, Double.MIN_VALUE};
		gbl_panel_1.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		panel_1.setLayout(gbl_panel_1);
		
		JLabel lblNewLabel = new JLabel("Client Info");
		GridBagConstraints gbc_lblNewLabel = new GridBagConstraints();
		gbc_lblNewLabel.insets = new Insets(0, 0, 5, 5);
		gbc_lblNewLabel.gridx = 2;
		gbc_lblNewLabel.gridy = 0;
		panel_1.add(lblNewLabel, gbc_lblNewLabel);
		
		JLabel lblSearchByClient = new JLabel("Search a Client");
		GridBagConstraints gbc_lblSearchByClient = new GridBagConstraints();
		gbc_lblSearchByClient.insets = new Insets(0, 0, 5, 5);
		gbc_lblSearchByClient.gridx = 1;
		gbc_lblSearchByClient.gridy = 1;
		panel_1.add(lblSearchByClient, gbc_lblSearchByClient);
		
		txtEnterClientId = new JTextField();
		txtEnterClientId.setText("Enter Client ID");
		GridBagConstraints gbc_txtEnterClientId = new GridBagConstraints();
		gbc_txtEnterClientId.insets = new Insets(0, 0, 5, 5);
		gbc_txtEnterClientId.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtEnterClientId.gridx = 1;
		gbc_txtEnterClientId.gridy = 2;
		panel_1.add(txtEnterClientId, gbc_txtEnterClientId);
		txtEnterClientId.setColumns(10);
		
		JButton btnClientSearch = new JButton("Search");
		btnClientSearch.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			//client search
			}
		});
		GridBagConstraints gbc_btnClientSearch = new GridBagConstraints();
		gbc_btnClientSearch.insets = new Insets(0, 0, 5, 5);
		gbc_btnClientSearch.gridx = 1;
		gbc_btnClientSearch.gridy = 3;
		panel_1.add(btnClientSearch, gbc_btnClientSearch);
		
		JLabel lblSearchResults_1 = new JLabel("Search Results");
		GridBagConstraints gbc_lblSearchResults_1 = new GridBagConstraints();
		gbc_lblSearchResults_1.insets = new Insets(0, 0, 5, 5);
		gbc_lblSearchResults_1.gridx = 3;
		gbc_lblSearchResults_1.gridy = 4;
		panel_1.add(lblSearchResults_1, gbc_lblSearchResults_1);
		
		JLabel lblClientId = new JLabel("Client ID");
		GridBagConstraints gbc_lblClientId = new GridBagConstraints();
		gbc_lblClientId.insets = new Insets(0, 0, 5, 5);
		gbc_lblClientId.gridx = 1;
		gbc_lblClientId.gridy = 5;
		panel_1.add(lblClientId, gbc_lblClientId);
		
		JLabel lblFirstName = new JLabel("First Name");
		GridBagConstraints gbc_lblFirstName = new GridBagConstraints();
		gbc_lblFirstName.insets = new Insets(0, 0, 5, 5);
		gbc_lblFirstName.gridx = 3;
		gbc_lblFirstName.gridy = 5;
		panel_1.add(lblFirstName, gbc_lblFirstName);
		
		txtClientIDSearch = new JTextField();
		txtClientIDSearch.setEditable(false);
		GridBagConstraints gbc_txtClientIDSearch = new GridBagConstraints();
		gbc_txtClientIDSearch.insets = new Insets(0, 0, 5, 5);
		gbc_txtClientIDSearch.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtClientIDSearch.gridx = 1;
		gbc_txtClientIDSearch.gridy = 6;
		panel_1.add(txtClientIDSearch, gbc_txtClientIDSearch);
		txtClientIDSearch.setColumns(10);
		
		txtFnameSearch = new JTextField();
		txtFnameSearch.setEditable(false);
		GridBagConstraints gbc_txtFnameSearch = new GridBagConstraints();
		gbc_txtFnameSearch.anchor = GridBagConstraints.NORTH;
		gbc_txtFnameSearch.insets = new Insets(0, 0, 5, 5);
		gbc_txtFnameSearch.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtFnameSearch.gridx = 3;
		gbc_txtFnameSearch.gridy = 6;
		panel_1.add(txtFnameSearch, gbc_txtFnameSearch);
		txtFnameSearch.setColumns(10);
		
		JLabel lblLastName = new JLabel("Last Name");
		GridBagConstraints gbc_lblLastName = new GridBagConstraints();
		gbc_lblLastName.insets = new Insets(0, 0, 5, 5);
		gbc_lblLastName.gridx = 1;
		gbc_lblLastName.gridy = 7;
		panel_1.add(lblLastName, gbc_lblLastName);
		
		JLabel lblItemsLoaned = new JLabel("Items Loaned");
		GridBagConstraints gbc_lblItemsLoaned = new GridBagConstraints();
		gbc_lblItemsLoaned.insets = new Insets(0, 0, 5, 5);
		gbc_lblItemsLoaned.gridx = 3;
		gbc_lblItemsLoaned.gridy = 7;
		panel_1.add(lblItemsLoaned, gbc_lblItemsLoaned);
		
		txtLnameSearch = new JTextField();
		txtLnameSearch.setEditable(false);
		GridBagConstraints gbc_txtLnameSearch = new GridBagConstraints();
		gbc_txtLnameSearch.anchor = GridBagConstraints.NORTH;
		gbc_txtLnameSearch.insets = new Insets(0, 0, 5, 5);
		gbc_txtLnameSearch.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtLnameSearch.gridx = 1;
		gbc_txtLnameSearch.gridy = 8;
		panel_1.add(txtLnameSearch, gbc_txtLnameSearch);
		txtLnameSearch.setColumns(10);
		
		txtLoanedSearch = new JTextField();
		txtLoanedSearch.setEditable(false);
		GridBagConstraints gbc_txtLoanedSearch = new GridBagConstraints();
		gbc_txtLoanedSearch.insets = new Insets(0, 0, 5, 5);
		gbc_txtLoanedSearch.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtLoanedSearch.gridx = 3;
		gbc_txtLoanedSearch.gridy = 8;
		panel_1.add(txtLoanedSearch, gbc_txtLoanedSearch);
		txtLoanedSearch.setColumns(10);
		
		JLabel lblEmailSearch = new JLabel("e-Mail");
		GridBagConstraints gbc_lblEmailSearch = new GridBagConstraints();
		gbc_lblEmailSearch.insets = new Insets(0, 0, 5, 5);
		gbc_lblEmailSearch.gridx = 1;
		gbc_lblEmailSearch.gridy = 9;
		panel_1.add(lblEmailSearch, gbc_lblEmailSearch);
		
		txtEmailSearch = new JTextField();
		txtEmailSearch.setEditable(false);
		GridBagConstraints gbc_txtEmailSearch = new GridBagConstraints();
		gbc_txtEmailSearch.insets = new Insets(0, 0, 5, 5);
		gbc_txtEmailSearch.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtEmailSearch.gridx = 1;
		gbc_txtEmailSearch.gridy = 10;
		panel_1.add(txtEmailSearch, gbc_txtEmailSearch);
		txtEmailSearch.setColumns(10);
		
		JLabel lblAddAClient = new JLabel("Add  a Client");
		GridBagConstraints gbc_lblAddAClient = new GridBagConstraints();
		gbc_lblAddAClient.insets = new Insets(0, 0, 5, 5);
		gbc_lblAddAClient.gridx = 3;
		gbc_lblAddAClient.gridy = 14;
		panel_1.add(lblAddAClient, gbc_lblAddAClient);
		
		JLabel lblClientId_1 = new JLabel("Client ID");
		GridBagConstraints gbc_lblClientId_1 = new GridBagConstraints();
		gbc_lblClientId_1.insets = new Insets(0, 0, 5, 5);
		gbc_lblClientId_1.gridx = 1;
		gbc_lblClientId_1.gridy = 15;
		panel_1.add(lblClientId_1, gbc_lblClientId_1);
		
		JLabel lblFirstName_1 = new JLabel("First Name");
		GridBagConstraints gbc_lblFirstName_1 = new GridBagConstraints();
		gbc_lblFirstName_1.insets = new Insets(0, 0, 5, 5);
		gbc_lblFirstName_1.gridx = 3;
		gbc_lblFirstName_1.gridy = 15;
		panel_1.add(lblFirstName_1, gbc_lblFirstName_1);
		
		txtClientIDSubmit = new JTextField();
		GridBagConstraints gbc_txtClientIDSubmit = new GridBagConstraints();
		gbc_txtClientIDSubmit.insets = new Insets(0, 0, 5, 5);
		gbc_txtClientIDSubmit.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtClientIDSubmit.gridx = 1;
		gbc_txtClientIDSubmit.gridy = 16;
		panel_1.add(txtClientIDSubmit, gbc_txtClientIDSubmit);
		txtClientIDSubmit.setColumns(10);
		
		txtFnameSubmit = new JTextField();
		GridBagConstraints gbc_txtFnameSubmit = new GridBagConstraints();
		gbc_txtFnameSubmit.insets = new Insets(0, 0, 5, 5);
		gbc_txtFnameSubmit.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtFnameSubmit.gridx = 3;
		gbc_txtFnameSubmit.gridy = 16;
		panel_1.add(txtFnameSubmit, gbc_txtFnameSubmit);
		txtFnameSubmit.setColumns(10);
		
		JLabel lblLastName_1 = new JLabel("Last Name");
		GridBagConstraints gbc_lblLastName_1 = new GridBagConstraints();
		gbc_lblLastName_1.insets = new Insets(0, 0, 5, 5);
		gbc_lblLastName_1.gridx = 1;
		gbc_lblLastName_1.gridy = 17;
		panel_1.add(lblLastName_1, gbc_lblLastName_1);
		
		JLabel label_8 = new JLabel("");
		GridBagConstraints gbc_label_8 = new GridBagConstraints();
		gbc_label_8.insets = new Insets(0, 0, 5, 5);
		gbc_label_8.gridx = 3;
		gbc_label_8.gridy = 17;
		panel_1.add(label_8, gbc_label_8);
		
		txtLnameSubmit = new JTextField();
		GridBagConstraints gbc_txtLnameSubmit = new GridBagConstraints();
		gbc_txtLnameSubmit.anchor = GridBagConstraints.NORTH;
		gbc_txtLnameSubmit.insets = new Insets(0, 0, 5, 5);
		gbc_txtLnameSubmit.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtLnameSubmit.gridx = 1;
		gbc_txtLnameSubmit.gridy = 18;
		panel_1.add(txtLnameSubmit, gbc_txtLnameSubmit);
		txtLnameSubmit.setColumns(10);
		
		JButton btnClientSubmit = new JButton("Submit");
		btnClientSubmit.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			//client add
			}
		});
		GridBagConstraints gbc_btnClientSubmit = new GridBagConstraints();
		gbc_btnClientSubmit.insets = new Insets(0, 0, 5, 5);
		gbc_btnClientSubmit.gridx = 3;
		gbc_btnClientSubmit.gridy = 18;
		panel_1.add(btnClientSubmit, gbc_btnClientSubmit);
		
		
		JLabel lblClientInvalid = new JLabel("");
		lblClientInvalid.setForeground(Color.RED);
		GridBagConstraints gbc_lblClientInvalid = new GridBagConstraints();
		gbc_lblClientInvalid.insets = new Insets(0, 0, 5, 5);
		gbc_lblClientInvalid.gridx = 3;
		gbc_lblClientInvalid.gridy = 19;
		panel_1.add(lblClientInvalid, gbc_lblClientInvalid);
		
		JLabel lblEmailSubmit = new JLabel("e-Mail");
		GridBagConstraints gbc_lblEmailSubmit = new GridBagConstraints();
		gbc_lblEmailSubmit.insets = new Insets(0, 0, 5, 5);
		gbc_lblEmailSubmit.gridx = 1;
		gbc_lblEmailSubmit.gridy = 20;
		panel_1.add(lblEmailSubmit, gbc_lblEmailSubmit);
		
		txtEmailSubmit = new JTextField();
		GridBagConstraints gbc_txtEmailSubmit = new GridBagConstraints();
		gbc_txtEmailSubmit.insets = new Insets(0, 0, 0, 5);
		gbc_txtEmailSubmit.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtEmailSubmit.gridx = 1;
		gbc_txtEmailSubmit.gridy = 21;
		panel_1.add(txtEmailSubmit, gbc_txtEmailSubmit);
		txtEmailSubmit.setColumns(10);
		
		
		JPanel panel = new JPanel();
		panel.setBackground(new Color(211, 211, 211));
		GridBagConstraints gbc_panel = new GridBagConstraints();
		gbc_panel.gridheight = 2;
		gbc_panel.fill = GridBagConstraints.BOTH;
		gbc_panel.gridx = 2;
		gbc_panel.gridy = 0;
		frame.getContentPane().add(panel, gbc_panel);
		GridBagLayout gbl_panel = new GridBagLayout();
		gbl_panel.columnWidths = new int[]{0, 0, 0, 0, 0, 0};
		gbl_panel.rowHeights = new int[]{0, 0, 0, 0, 0, 0};
		gbl_panel.columnWeights = new double[]{0.0, 0.0, 1.0, 0.0, 1.0, Double.MIN_VALUE};
		gbl_panel.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 1.0, Double.MIN_VALUE};
		panel.setLayout(gbl_panel);
		
		JLabel lblNewLabel_1 = new JLabel("Client Book List");
		GridBagConstraints gbc_lblNewLabel_1 = new GridBagConstraints();
		gbc_lblNewLabel_1.insets = new Insets(0, 0, 5, 5);
		gbc_lblNewLabel_1.gridx = 2;
		gbc_lblNewLabel_1.gridy = 0;
		panel.add(lblNewLabel_1, gbc_lblNewLabel_1);
		
		txtClientName = new JTextField();
		txtClientName.setText("Client Name");
		GridBagConstraints gbc_txtClientName = new GridBagConstraints();
		gbc_txtClientName.insets = new Insets(0, 0, 5, 5);
		gbc_txtClientName.fill = GridBagConstraints.HORIZONTAL;
		gbc_txtClientName.gridx = 2;
		gbc_txtClientName.gridy = 1;
		panel.add(txtClientName, gbc_txtClientName);
		txtClientName.setColumns(10);
		
		JLabel lblBookList = new JLabel("Book List");
		GridBagConstraints gbc_lblBookList = new GridBagConstraints();
		gbc_lblBookList.insets = new Insets(0, 0, 5, 5);
		gbc_lblBookList.gridx = 2;
		gbc_lblBookList.gridy = 3;
		panel.add(lblBookList, gbc_lblBookList);
		
		JTextArea txtArea = new JTextArea();
		txtArea.setEditable(false);
		txtArea.setWrapStyleWord(true);
		txtArea.setLineWrap(true);
		GridBagConstraints gbc_txtr = new GridBagConstraints();
		gbc_txtr.gridwidth = 3;
		gbc_txtr.insets = new Insets(0, 0, 0, 5);
		gbc_txtr.fill = GridBagConstraints.BOTH;
		gbc_txtr.gridx = 1;
		gbc_txtr.gridy = 4;
		panel.add(txtArea, gbc_txtr);
		
		/**
		 * When the button is pressed search the item map for the item with the serial number in the textField			
		 */
		btnItemSearch.addActionListener(new ActionListener() {

public void actionPerformed(ActionEvent e) {
			if(e.getSource() == btnItemSearch){
				System.out.println( "Item Search button was pressed");
				if(itemDb.map.containsKey(txtEnterSerial.getText())){
					Item item = itemDb.map.get(txtEnterSerial.getText());
					txtSerialSearch.setText(item.getSerialNumber());
					txtTitleSearch.setText(item.getTitle());
					txtArtistSearch.setText(item.getArtist());
					txtAlbumSearch.setText(item.getAlbum());
					txtYearSearch.setText(item.getYear());
					txtTypeSearch.setText(item.getType());
					txtLocationSearch.setText(item.getLocation());
				}else{
					txtEnterSerial.setText("Wrong Serial Number");
				}
			}
			
			}
		});

		/**
		 * When the button is pressed submit item a new to the item map  			
		 */
		btnItemSubmit.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if(e.getSource() == btnItemSubmit){
					System.out.println("Item Submit button was pressed");
					labelItemInvalid.setText(" ");
					String [] info = new String [7];
					info[0] = txtSerialSubmit.getText();
					info[1] = txtTypeSubmit.getText();
					info[2] = txtTitleSubmit.getText();
					info[3] = txtArtistSubmit.getText();
					info[4] = txtAlbumSubmit.getText();
					info[5] = txtYearSubmit.getText();
					info[6] = txtLocationSubmit.getText();
					for(int i = 0; i< 7; i++){
						if(info[i].isEmpty()){ 
							info[0] ="false";
							break;
						}
					}
					if(itemDb.getMap().containsKey(info[0]) || info[0]== "false"){
						System.out.println("Invalid Entry");
						labelItemInvalid.setText("Invalid Entry");	
					}else{
						Item newEntry = new Item(info[0], info[1], info[2], info[3], info[4], info[5], info[6]);
						itemDb.addEntry(newEntry);
					}
				}
			}
		});
		/**
		 * When the button is pressed search the client map for the item with the client ID in the textField			
		 */
		btnClientSearch.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			if(e.getSource() == btnClientSearch){
				System.out.println("Client Search button was pressed");
				if(clientDb.getMap().containsKey(txtEnterClientId.getText())){
					Client client = clientDb.map.get(txtEnterClientId.getText());
					txtClientIDSearch.setText(client.getClientID());
					txtFnameSearch.setText(client.getFirstName());
					txtLnameSearch.setText(client.getLastName());
					txtLoanedSearch.setText(String.valueOf((client.itemsLoaned.size())));
					txtEmailSearch.setText(client.getEmail());
					
					txtClientName.setText(client.getFirstName() + " " + client.getLastName());
					for(int i =0; i<client.getItemsLoaned().size(); i++){
						Item item = client.getItemsLoaned().get(i);
						txtArea.append("Item " + (i+1) + ": " +  item.getTitle() + " " + item.getLocation() + "/n");
					}if(client.getItemsLoaned().size() == 0){
						txtArea.append("No Items Loaned By this user");
					}
					
				}else{
					txtEnterClientId.setText("Wrong Serial Number");
					
					txtArea.setText("");
				}
			}
			
			}
		});
		
		/**
		 * When the button is pressed submit item a new to the item map  			
		 */
		btnClientSubmit.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if(e.getSource() == btnClientSubmit){
					System.out.println("Client Submit button was pressed");
					lblClientInvalid.setText(" ");
					String [] info = new String [4];
					info[0] = txtClientIDSubmit.getText();
					info[1] = txtFnameSubmit.getText();
					info[2] = txtLnameSubmit.getText();
					info[3] = txtEmailSubmit.getText();
					for(int i = 0; i< 4; i++){
						if(info[i].isEmpty()){ 
							info[0] ="false";
							break;
						}
					}
					if(clientDb.getMap().containsKey(info[0]) || info[0]== "false"){
						System.out.println("Invalid Entry");
						lblClientInvalid.setText("Invalid Entry");	
					}else{
						Client newEntry = new Client(info[0], info[1], info[2], info[3] );
						clientDb.addEntry(newEntry);
					}
				}
			}
		});	
		
		
		
		
		
		frame.setBounds(100, 100, 1019, 682);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	
	
	}

}
